### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Kolaotse** [Krocified/ScreenStitch_Image-Stitcher#1]
I'm most likely doing something wrong but not sure what

Console:
PS C:\Users\Käyttäjä\Desktop\VSC>  & 'C:\Users\Käyttäjä\AppData\Local\Microsoft\WindowsApps\python3.11.exe' 'c:\Users\Käyttäjä\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '53512' '--' 'C:\Users\Käyttäjä\Desktop\VSC\screenstitch2.py' 
[ WARN:0@56.590] global loadsave.cpp:248 cv::findDecoder imread_('C:/Users/K├ñytt├ñj├ñ/Pictures/Screenshots/Screenshot (5).png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\Kõyttõjõ\Desktop\VSC\screenstitch2.py", line 75, in stitchImage
    image = imutils.rotate_bound(image, 90)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kõyttõjõ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\imutils\convenience.py", line 44, in rotate_bound
    (h, w) = image.shape[:2]
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Sat-Yo** [comment]
ChatGPT 😁:

The error indicates that the image variable is None, which means that the program failed to read the image file specified. This likely occurred because the file path provided is invalid or the file cannot be accessed. The issue seems to stem from the file path encoding, as characters like ä and ö are not being handled correctly. Here's how you can troubleshoot and fix the issue:

Steps to Fix:
Verify the File Path:

Ensure that the file exists at the specified path (C:/Users/Käyttäjä/Pictures/Screenshots/Screenshot (5).png).
Check that you have the necessary permissions to access the file.
Handle Special Characters:

Python might have issues with non-ASCII characters in file paths. Ensure the path is correctly encoded.
Use a raw string (r"your_path") or double backslashes (\\) in the path:
python
Copy code
image_path = r"C:\Users\Käyttäjä\Pictures\Screenshots\Screenshot (5).png"
Check cv2.imread:

Verify if cv2.imread successfully loads the image:
python
Copy code
import cv2
image_path = r"C:\Users\Käyttäjä\Pictures\Screenshots\Screenshot (5).png"
image = cv2.imread(image_path)
if image is None:
    print("Failed to load image. Check the file path and format.")
Debug Path Issues:

Replace the problematic characters with their Unicode representation or use os.path to build paths dynamically:
python
Copy code
import os
image_path = os.path.join("C:", "Users", "Käyttäjä", "Pictures", "Screenshots", "Screenshot (5).png")
Fallback: Rename the Folder:

If all else fails, rename the folder Käyttäjä to remove special characters and update the path accordingly.
Rotate Bound Check:

Ensure the imutils.rotate_bound function is only called if the image is successfully loaded:
python
Copy code
if image is not None:
    rotated_image = imutils.rotate_bound(image, 90)
else:
    print("Image loading failed, skipping rotation.")
Final Thoughts
Fixing the file path should resolve the issue. If the problem persists, ensure that all dependencies (opencv-python, imutils, etc.) are correctly installed and up-to-date. Let me know if you need more guidance!

**Comment by Sat-Yo** [comment]
@Kolaotse

**Comment by Krocified** [comment]
Fixed, thanks for your input
